// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAAC-vdt1jHJ_NVwPcyRssRYcb2e70PBMk",
    appId: "1:898165572209:web:bd7ef6b5125d4af00451d0",
    messagingSenderId: "898165572209",
    projectId: "crewcallflutter",
  storageBucket: "crewcallflutter.firebasestorage.app",
    authDomain: "crewcallflutter.firebaseapp.com",
      measurementId: "G-K1TEHV3ZD0"
    // storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: "AIzaSyAAC-vdt1jHJ_NVwPcyRssRYcb2e70PBMk",
    appId: "1:898165572209:web:bd7ef6b5125d4af00451d0",
    messagingSenderId: "898165572209",
    projectId: "crewcallflutter",
  storageBucket: "crewcallflutter.firebasestorage.app",
    authDomain: "crewcallflutter.firebaseapp.com",
      measurementId: "G-K1TEHV3ZD0"
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: "AIzaSyAAC-vdt1jHJ_NVwPcyRssRYcb2e70PBMk",
  //   appId: 'YOUR_IOS_APP_ID',
  //   messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
  //   projectId: 'YOUR_PROJECT_ID',
  //   storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  //   iosBundleId: 'com.example.crewcallFlutter',
  // );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: "AIzaSyAAC-vdt1jHJ_NVwPcyRssRYcb2e70PBMk",
//     appId: 'YOUR_MACOS_APP_ID',
//     messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
//     projectId: 'YOUR_PROJECT_ID',
//     storageBucket: 'YOUR_PROJECT_ID.appspot.com',
//     iosBundleId: 'com.example.crewcallFlutter',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: "AIzaSyAAC-vdt1jHJ_NVwPcyRssRYcb2e70PBMk",
//     appId: 'YOUR_WINDOWS_APP_ID',
//     messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
//     projectId: 'YOUR_PROJECT_ID',
//     authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
//     storageBucket: 'YOUR_PROJECT_ID.appspot.com',
//   );
}